import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class TrashcanService {
    private DatabaseManager dbManager;

    public TrashcanService(DatabaseManager dbManager) {
        this.dbManager = dbManager;
    }

    /**
     * Fetches all trashcans from the database.
     * 
     * @return List of all Trashcan objects, empty list if none found or error occurs
     */
    public List<Trashcan> getAllTrashcans() {
        List<Trashcan> trashcans = new ArrayList<>();
        Connection conn = dbManager.getConnection();

        if (conn == null) {
            System.err.println("[ERROR] Error: No database connection available.");
            return trashcans;
        }

        String sql = "SELECT id, name, location, status, last_updated FROM trashcans ORDER BY id";

        try (PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                Trashcan trashcan = new Trashcan(
                    rs.getInt("id"),
                    rs.getString("name"),
                    rs.getString("location"),
                    rs.getString("status"),
                    rs.getTimestamp("last_updated")
                );
                trashcans.add(trashcan);
            }

            if (trashcans.isEmpty()) {
                System.out.println("No trashcans found in database.");
            } else {
                System.out.println("[OK] Retrieved " + trashcans.size() + " trashcan(s) from database.");
            }

        } catch (SQLException e) {
            System.err.println("[ERROR] Error fetching trashcans: " + e.getMessage());
            System.err.println("  SQL State: " + e.getSQLState());
            System.err.println("  Error Code: " + e.getErrorCode());
        }

        return trashcans;
    }

    /**
     * Adds a new trashcan to the database.
     * The trashcan's ID will be auto-generated by the database.
     * 
     * @param trashcan The Trashcan object to insert (id will be ignored)
     */
    public void addTrashcan(Trashcan trashcan) {
        if (trashcan == null) {
            System.err.println("[ERROR] Error: Cannot add null trashcan.");
            return;
        }

        Connection conn = dbManager.getConnection();
        if (conn == null) {
            System.err.println("[ERROR] Error: No database connection available.");
            return;
        }

        String sql = "INSERT INTO trashcans (name, location, status, last_updated) VALUES (?, ?, ?, ?)";

        try (PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            pstmt.setString(1, trashcan.getName());
            pstmt.setString(2, trashcan.getLocation());
            pstmt.setString(3, trashcan.getStatus());
            
            // Use provided timestamp or current timestamp
            if (trashcan.getLastUpdated() != null) {
                pstmt.setTimestamp(4, trashcan.getLastUpdated());
            } else {
                pstmt.setTimestamp(4, new Timestamp(System.currentTimeMillis()));
            }

            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                // Retrieve the generated ID
                try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        int newId = generatedKeys.getInt(1);
                        trashcan.setId(newId);
                        System.out.println("[OK] Successfully added trashcan with ID: " + newId);
                    }
                }
            } else {
                System.err.println("[ERROR] Error: No rows were inserted.");
            }

        } catch (SQLException e) {
            System.err.println("[ERROR] Error adding trashcan: " + e.getMessage());
            System.err.println("  SQL State: " + e.getSQLState());
            System.err.println("  Error Code: " + e.getErrorCode());
            
            // Provide specific error messages
            if (e.getMessage().contains("violates check constraint")) {
                System.err.println("  Hint: Status must be one of: 'empty', 'half', 'full'");
            } else if (e.getMessage().contains("null value")) {
                System.err.println("  Hint: Name is required and cannot be null");
            }
        }
    }

    /**
     * Updates an existing trashcan in the database.
     * Updates name, location, and status. The last_updated timestamp is automatically updated.
     * 
     * @param trashcan The Trashcan object with updated values (must have a valid id)
     */
    public void updateTrashcan(Trashcan trashcan) {
        if (trashcan == null) {
            System.err.println("[ERROR] Error: Cannot update null trashcan.");
            return;
        }

        if (trashcan.getId() <= 0) {
            System.err.println("[ERROR] Error: Invalid trashcan ID. Cannot update trashcan without a valid ID.");
            return;
        }

        Connection conn = dbManager.getConnection();
        if (conn == null) {
            System.err.println("[ERROR] Error: No database connection available.");
            return;
        }

        String sql = "UPDATE trashcans SET name = ?, location = ?, status = ?, last_updated = CURRENT_TIMESTAMP WHERE id = ?";

        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, trashcan.getName());
            pstmt.setString(2, trashcan.getLocation());
            pstmt.setString(3, trashcan.getStatus());
            pstmt.setInt(4, trashcan.getId());

            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("[OK] Successfully updated trashcan with ID: " + trashcan.getId());
            } else {
                System.err.println("[ERROR] Error: No trashcan found with ID: " + trashcan.getId());
            }

        } catch (SQLException e) {
            System.err.println("[ERROR] Error updating trashcan: " + e.getMessage());
            System.err.println("  SQL State: " + e.getSQLState());
            System.err.println("  Error Code: " + e.getErrorCode());
            
            if (e.getMessage().contains("violates check constraint")) {
                System.err.println("  Hint: Status must be one of: 'empty', 'half', 'full'");
            }
        }
    }

    /**
     * Deletes a trashcan from the database by ID.
     * 
     * @param id The ID of the trashcan to delete
     */
    public void deleteTrashcan(int id) {
        if (id <= 0) {
            System.err.println("[ERROR] Error: Invalid trashcan ID. ID must be greater than 0.");
            return;
        }

        Connection conn = dbManager.getConnection();
        if (conn == null) {
            System.err.println("[ERROR] Error: No database connection available.");
            return;
        }

        String sql = "DELETE FROM trashcans WHERE id = ?";

        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, id);

            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("[OK] Successfully deleted trashcan with ID: " + id);
            } else {
                System.err.println("[ERROR] Error: No trashcan found with ID: " + id);
            }

        } catch (SQLException e) {
            System.err.println("[ERROR] Error deleting trashcan: " + e.getMessage());
            System.err.println("  SQL State: " + e.getSQLState());
            System.err.println("  Error Code: " + e.getErrorCode());
            
            if (e.getMessage().contains("violates foreign key constraint")) {
                System.err.println("  Hint: Cannot delete trashcan. There are subscriptions referencing this trashcan.");
            }
        }
    }

    /**
     * Saves a list of trashcans to the database.
     * Uses batch insert for efficiency. Existing trashcans (with IDs) are skipped.
     * 
     * @param trashcans List of Trashcan objects to save
     */
    public void saveTrashcans(List<Trashcan> trashcans) {
        if (trashcans == null || trashcans.isEmpty()) {
            System.out.println("No trashcans to save.");
            return;
        }

        Connection conn = dbManager.getConnection();
        if (conn == null) {
            System.err.println("[ERROR] Error: No database connection available.");
            return;
        }

        String sql = "INSERT INTO trashcans (name, location, status, last_updated) VALUES (?, ?, ?, ?)";

        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            int batchCount = 0;
            int savedCount = 0;

            for (Trashcan trashcan : trashcans) {
                if (trashcan == null) {
                    continue;
                }

                // Skip trashcans that already have an ID (they're already in DB)
                if (trashcan.getId() > 0) {
                    System.out.println("Skipping trashcan with ID " + trashcan.getId() + " (already exists in database).");
                    continue;
                }

                pstmt.setString(1, trashcan.getName());
                pstmt.setString(2, trashcan.getLocation());
                pstmt.setString(3, trashcan.getStatus());
                
                if (trashcan.getLastUpdated() != null) {
                    pstmt.setTimestamp(4, trashcan.getLastUpdated());
                } else {
                    pstmt.setTimestamp(4, new Timestamp(System.currentTimeMillis()));
                }

                pstmt.addBatch();
                batchCount++;

                // Execute batch every 100 items to avoid memory issues
                if (batchCount % 100 == 0) {
                    int[] results = pstmt.executeBatch();
                    for (int result : results) {
                        if (result > 0) savedCount++;
                    }
                    pstmt.clearBatch();
                }
            }

            // Execute remaining batch items
            if (batchCount % 100 != 0) {
                int[] results = pstmt.executeBatch();
                for (int result : results) {
                    if (result > 0) savedCount++;
                }
            }

            System.out.println("[OK] Successfully saved " + savedCount + " out of " + trashcans.size() + " trashcan(s) to database.");

        } catch (SQLException e) {
            System.err.println("[ERROR] Error saving trashcans: " + e.getMessage());
            System.err.println("  SQL State: " + e.getSQLState());
            System.err.println("  Error Code: " + e.getErrorCode());
        }
    }

    /**
     * Displays all trashcans in a formatted table with wider columns.
     * 
     * @param trashcans List of Trashcan objects to display
     */
    public void displayTrashcans(List<Trashcan> trashcans) {
        if (trashcans == null || trashcans.isEmpty()) {
            System.out.println("No trashcans to display.");
            return;
        }

        // Print table header with wider columns
        System.out.println("+-----+---------------------------------------------+----------------------------------------+----------+---------------------+");
        System.out.println("| ID  | Name                                         | Location                                | Status   | Last Updated         |");
        System.out.println("+-----+---------------------------------------------+----------------------------------------+----------+---------------------+");

        // Print each trashcan
        for (Trashcan trashcan : trashcans) {
            System.out.println(trashcan.toString());
        }

        // Print table footer
        System.out.println("+-----+---------------------------------------------+----------------------------------------+----------+---------------------+");
        System.out.println("Total: " + trashcans.size() + " trashcan(s)");
    }
    
    /**
     * Displays a single trashcan in detail without truncation.
     * 
     * @param trashcan The Trashcan object to display
     */
    public void displayTrashcanDetail(Trashcan trashcan) {
        if (trashcan == null) {
            System.out.println("[ERROR] Error: Cannot display null trashcan.");
            return;
        }
        
        System.out.println(trashcan.toDetailedString());
    }
}

